@startuml
title US-4: As an Administrator I want to see the Top 5 physicians based on the number of appointments

autonumber
autoactivate on

actor "Administrator" as admin
participant "PhysicianAPI" as api
participant "AuthContext" as auth
participant "PhysicianService" as service
participant "PhysicianRepository" as repo
participant "AppointmentRepository" as apptRepo
participant "Mapper: PhysicianViewMapper" as viewMapper
participant "obj: Physician" as physician


admin -> api : GET /physician/top5\n
api -> auth : getAuthenticatedUser()
auth --> api : AdminUserDetails


api -> service : getTop5ByAppointmentCount()


service -> repo : findTop5ByAppointmentCount()
repo --> service : List<Physician>


loop for each physician
    service -> viewMapper : toStatsDTO(physician)
    viewMapper --> service : PhysicianStatsDTO
end

service --> api : List<PhysicianStatsDTO>
api --> admin : HTTP 200 OK + body(List<PhysicianStatsDTO>)

@enduml
