@startuml
title US-14: As Physician, I want to search the appointment records of a patient

autonumber
autoactivate on

actor "Physician" as physician
participant "AppointmentRecordController" as api
participant "AppointmentRecordService" as service
participant "repo: AppointmentRecordRepository" as repo

physician -> api : GET /api/appointmentRecords/search/{patientNumber}/{recordNumber}
api -> service : searchAppointmentRecordByPatient(page, patientNumber, recordNumber)

service -> repo : searchByPatientNumberAndRecordNumber(patientNumber, recordNumber)
repo --> service : List<AppointmentRecord>

alt records empty
    service --> api : throw NotFoundStatusException
    api --> physician : HTTP 404 Not Found
else records found
    service --> api : records
    api --> physician : HTTP 200 OK + body(List<AppointmentRecord>)
end

@enduml