@startuml
title US17: As Administrator or Patient I want to view an appointment record by record number

autonumber
autoactivate on

actor "Administrator/Patient" as user
participant "AppointmentAPI" as api
participant "AppointmentRecordService" as service
participant "ViewMapper: AppointmentRecordViewMapper" as viewMapper
participant "repo: AppointmentRecordRepository" as recordRepo
participant "Security: AuthContext" as auth


user -> api : GET /records/{recordNumber}\n

api -> auth : getAuthenticatedUser()
auth --> api : UserDetails (Admin or Patient)

api -> service : getAppointmentRecordByNumber(recordNumber, authenticatedUser)


service -> recordRepo : findByRecordNumber(recordNumber)
recordRepo --> service : Optional<AppointmentRecord>

service -> service : validateAccessPermission(record, authenticatedUser)


service -> viewMapper : toDTO(record)
viewMapper --> service : AppointmentRecordViewDTO
service --> api : AppointmentRecordViewDTO
api --> user : HTTP 200 OK + body(AppointmentRecordViewDTO)

@enduml
