@startuml ClinicDomainModel

hide methods
title Domain Model for the Healthcare Administration Platform (HAP)

package "Patient Service"{
    object Patient {
        id
        patientNumber
        emailAddress
        user
        name
        dateOfBirth
        phoneNumber
        ddress
        enabled
        insuranceInformation
        dataConsent
    }
    object HealthConcerns {
        id
        description
        dateIdentified
        treatment
        stillOngoing
        dateResolved
        patient
    }
}

package "Physician Service"{
    object Physician {
        id
        name
        address
        physicianNumber
        user
        phoneNumber
        emailAddress
        enabled
        department
        specialty
        workingHours
        profilePicture
    }
}

package "Appointment Service" {
    object Appointment {
        patientNumber
        physicianNumber
    }
    object AppointmentDateTime {
        dateTime
    }
    object AppointmentNumber {
        value
    }
    object AppointmentStatus {
        SCHEDULED
        COMPLETED
        CANCELLED
        RESCHEDULED
    }
    object ConsultationType {
        GENERAL
        DENTAL
        PEDIATRIC
        CARDIOLOGY
        DERMATOLOGY
    }

    object AppointmentRecord {
        id
        diagnosis
        treatmentRecommendation
        prescription
        recordNumber
    }
}

object User {
	id
	version
	createdAt
	modifiedAt
	createdBy
	modifiedBy
	enabled
	username
	password
	fullName
	authorities
}

object Role {
	PATIENT
	PHYSICIAN
	ADMIN
}

Appointment "1"-L-"1" AppointmentDateTime
Appointment "1"--"1" AppointmentNumber
Appointment "1"--"1" AppointmentStatus
Appointment "1"--"1" ConsultationType
Appointment "1"--"1" AppointmentRecord

Patient "1"--"1" HealthConcerns

User "1"--"*" Role
User "1"-D-"*" Patient
User "1"-D-"*" Physician

Appointment "*"-U-"1" Physician
Appointment "*"-U-"1" Patient

@enduml