@startuml
title US15: As Physician I want to view the appointment records of a patient

autonumber
autoactivate on

actor "Physician" as physician
participant "AppointmentAPI" as api
participant "AppointmentRecordService" as service
participant "ViewMapper: AppointmentRecordViewMapper" as viewMapper
participant "repo: AppointmentRecordRepository" as recordRepo
participant "Security: AuthContext" as auth


physician -> api : GET /patients/{patientNumber}/records\nAuthorization: Bearer token
api -> auth : getAuthenticatedUser()
auth --> api : PhysicianUserDetails

api -> service : getAppointmentRecordsByPatient(patientNumber, authenticatedUser)


service -> service : validatePhysicianPermission(patientNumber, authenticatedUser)
service -> recordRepo : findByPatientNumber(patientNumber)
recordRepo --> service : List<AppointmentRecord>


service -> viewMapper : toDTOList(records)
viewMapper --> service : List<AppointmentRecordViewDTO>
service --> api : List<AppointmentRecordViewDTO>
api --> physician : HTTP 200 OK + body(List<AppointmentRecordViewDTO>)

@enduml
