@startuml SagaChoreography

title US Appointment Schedule

actor Patient

participant Gateway as "API Gateway"
participant AppointSvc as "Appointment Service (Instance X)"
box "Appointment Service"
participant AppointSvc_Controller as "Appointment Service Controller"
participant AppointSvc_Service as "Appointment Service Service"
participant AppointSvc_Repository as "Appointment Service Repository"
end box
participant PatientSvc as "Patient Service (Instance X)"
participant PhysicianSvc as "Physician Service (Instance X)"

Patient -> Gateway : Asks to schedule appointment
activate Patient
activate Gateway
Gateway -> AppointSvc : POST api/appointments/scheduleAppointment \n Headers(Bearer Token) \n Json Body(physicianNumber, dateTime, consultationType)
activate AppointSvc
AppointSvc -> AppointSvc_Controller : scheduleAppointment(request)
activate AppointSvc_Controller
AppointSvc_Controller -> AppointSvc_Service : scheduleAppointmentByPatient(physicianNumber,\ndateTime, consultationType)
activate AppointSvc_Service
AppointSvc_Service -> PatientSvc : restTemplate.getForObject(getPatientUrl, String.class);

note left
    Synchronous Call Using HTTP
    instead of asynchronous because we
    need the data before the end
    of the schedule operation
end note

activate PatientSvc
PatientSvc --> AppointSvc_Service : returns(patient)
deactivate PatientSvc

alt patient service doesn't respond with valid patient
AppointSvc_Service --> AppointSvc_Controller : error checking if patient exists
AppointSvc_Controller --> AppointSvc : error checking if patient exists
AppointSvc --> Gateway : error checking if patient exists
Gateway --> Patient : unable to schedule appointment
end

AppointSvc_Service -> PhysicianSvc : restTemplate.getForObject(getPhysicianUrl, String.class);

note left
    Synchronous Call Using HTTP
    instead of asynchronous because we
    need the data before the end
    of the schedule operation
end note

activate PhysicianSvc
PhysicianSvc --> AppointSvc_Service : returns(physician)
deactivate PhysicianSvc

alt physician service doesn't respond with valid physician
AppointSvc_Service --> AppointSvc_Controller : error checking if physician exists
AppointSvc_Controller --> AppointSvc : error checking if physician exists
AppointSvc --> Gateway : error checking if physician exists
Gateway --> Patient : unable to schedule appointment
end

AppointSvc_Service -> AppointSvc_Repository : save(appointment)
activate AppointSvc_Repository
AppointSvc_Repository --> AppointSvc_Service : created

deactivate AppointSvc_Repository
AppointSvc_Service --> AppointSvc_Controller : created
deactivate AppointSvc_Service
AppointSvc_Controller --> AppointSvc : created
deactivate AppointSvc_Controller
AppointSvc --> Gateway : created
deactivate Gateway
Gateway --> Patient : created
deactivate Patient

@enduml