@startuml SagaChoreography

title US Appointment Schedule

actor Patient

participant Gateway as "API Gateway"
box "Appointment Service (Instance X)"
participant AppointSvc_Controller as "Appointment Service Controller"
participant AppointSvc_Service as "Appointment Service Service"
participant AppointSvc_Repository as "Appointment Service Repository"
end box
participant PatientSvc as "Patient Service (Instance X)"
participant PhysicianSvc as "Physician Service (Instance X)"
queue Broker as "RabbitMQ"

Patient -> Gateway : Asks to schedule appointment
activate Patient
activate Gateway
Gateway -> AppointSvc_Controller : POST api/appointments/scheduleAppointment \n Headers(Bearer Token) \n Json Body(physicianNumber, dateTime, consultationType)

activate AppointSvc_Controller
AppointSvc_Controller -> AppointSvc_Service : scheduleAppointmentByPatient(physicianNumber,\ndateTime, consultationType)
activate AppointSvc_Service
AppointSvc_Service -> Broker : publish AppointmentRequestedEvent
activate Broker
Broker --> PhysicianSvc : subscribes AppointmentRequestedEvent
activate PhysicianSvc
PhysicianSvc -> PhysicianSvc : checks Physician WorkingHours
alt successful case
PhysicianSvc -> Broker : publish PhysicianBooked
else some kind of failure
PhysicianSvc -> Broker : publish PhysicianBookedFail
end
Broker --> PatientSvc : subscribes PhysicianBooked
activate PatientSvc
PatientSvc -> PatientSvc : checks PatientId
alt successful case
PatientSvc -> Broker : publish PatientBooked
else some kind of failure
PatientSvc -> Broker : publish PatientBookedFail
end
alt successful case
Broker --> AppointSvc_Service : consumes PhysicianBooked AND PatientBooked
AppointSvc_Service -> AppointSvc_Repository : save(appointment)
activate AppointSvc_Repository
AppointSvc_Repository --> AppointSvc_Service : created
deactivate AppointSvc_Repository
AppointSvc_Service --> AppointSvc_Controller : created
Gateway --> Patient : created
else some kind of failure
Broker --> AppointSvc_Service : consumes PhysicianBookedFail OR PatientBookedFail
deactivate Broker
PatientSvc -> PatientSvc : compensate
PhysicianSvc -> PhysicianSvc : compensate
deactivate PatientSvc
AppointSvc_Service --> AppointSvc_Controller : failed
deactivate AppointSvc_Service
deactivate PhysicianSvc
AppointSvc_Controller --> Gateway : failed
deactivate AppointSvc_Controller
Gateway --> Patient : failed
deactivate Gateway
deactivate PatientSvc
deactivate Patient
end
deactivate PhysicianSvc

@enduml