@startuml
'https://plantuml.com/sequence-diagram
title WP2A-14:As a Patient or Administrator, I want to view the details of an appointment given its appointment number.

actor User
participant "AppointmentController" as Controller
participant "AppointmentService" as Service
participant "AppointmentRepository" as Repository
participant "AppointmentMapper" as Mapper
database "Database"

User -> Controller : GET /appointments/{id}
activate Controller

Controller -> Service : getAppointmentById(id)
activate Service

Service -> Repository : findById(id)
activate Repository

Repository -> Database : SELECT * FROM appointment WHERE id=…
Database --> Repository : Appointment
deactivate Database

Repository --> Service : Appointment
deactivate Repository

Service --> Controller : Appointment
deactivate Service

Controller -> Mapper : toView(Appointment)
activate Mapper

Mapper --> Controller : AppointmentView
deactivate Mapper

Controller --> User : 200 OK\nAppointmentView
deactivate Controller
@enduml


